[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Harmonics"
authors = [{name = "Yuyao Liu", email = "yliuow@connect.ust.hk"}]
dynamic = ["version", "description"]
